server:
  port: 8082

#redis配置
redisson:
  address: redis://192.168.196.196:6379
  #password: xefredis13579@#$%
  #sentinelAddresses:
  #masterName:

#rocketMQ配置
rocketmq:
    namesrvAddr: 192.168.196.196:9876

dubbo:
  registry:
    address: zookeeper://192.168.196.196:2181
  protocol:
    port: 20880
    name: dubbo
  application:
    name: dubbo-service-consumer
  consumer:
    timeout: 5000
bob:
  service:
    version: 1.0.0
