server:
  port: 8082

#redis配置
redisson:
  address: redis://192.168.8.103:6380
  password: xefredis13579@#$%
  #sentinelAddresses:
  #masterName:

#rocketMQ配置
rocketmq:
    namesrvAddr: localhost:9876

dubbo:
  registry:
    address: zookeeper://localhost:2181
  protocol:
    port: 20880
    name: dubbo
  application:
    name: dubbo-service-consumer
  consumer:
    timeout: 5000
bob:
  service:
    version: 1.0.0
